"""add comuni

Revision ID: 0e5404663496
Revises: 117d2d0d04c3
Create Date: 2023-03-18 15:16:35.078990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5404663496'
down_revision = '117d2d0d04c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comuni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('istat', sa.Integer(), nullable=False),
    sa.Column('abitanti', sa.Integer(), nullable=False),
    sa.Column('CAP', sa.Integer(), nullable=False),
    sa.Column('codice_fiscale', sa.String(length=5), nullable=False),
    sa.Column('prefisso', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provincia'], ['province.id'], name='fk_comuni_province_id_provincia'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comuni')
    # ### end Alembic commands ###
