"""add sigla

Revision ID: 117d2d0d04c3
Revises: 81b2babbd38b
Create Date: 2023-03-17 22:13:53.012607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117d2d0d04c3'
down_revision = '81b2babbd38b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=2), nullable=False),
    sa.Column('superficie', sa.Integer(), nullable=False),
    sa.Column('abitanti', sa.Integer(), nullable=False),
    sa.Column('regione', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regione'], ['regioni.id'], name='fk_province_regioni_id_regione'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('comuni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('superficie', sa.Integer(), nullable=False),
    sa.Column('abitanti', sa.Integer(), nullable=False),
    sa.Column('regione', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regione'], ['province.id'], name='fk_comuni_province_id_regione'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comuni')
    op.drop_table('province')
    # ### end Alembic commands ###
