"""database creation

Revision ID: 265faa20975d
Revises: 
Create Date: 2023-03-20 12:45:00.053499

"""
from alembic import op
import sqlalchemy as sa
import ormar

# revision identifiers, used by Alembic.
revision = '265faa20975d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('capoluogo', sa.String(length=100), nullable=False),
    sa.Column('superficie', sa.Integer(), nullable=False),
    sa.Column('abitanti', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('users',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=4), nullable=False),
    sa.Column('superficie', sa.Integer(), nullable=False),
    sa.Column('abitanti', sa.Integer(), nullable=False),
    sa.Column('regione', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regione'], ['regioni.id'], name='fk_province_regioni_id_regione'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('comuni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('istat', sa.Integer(), nullable=False),
    sa.Column('abitanti', sa.Integer(), nullable=False),
    sa.Column('CAP', sa.Integer(), nullable=False),
    sa.Column('codice_fiscale', sa.String(length=5), nullable=False),
    sa.Column('prefisso', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provincia'], ['province.id'], name='fk_comuni_province_id_provincia'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comuni')
    op.drop_table('province')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('regioni')
    # ### end Alembic commands ###
