"""database creation

Revision ID: 365c2914f700
Revises: 
Create Date: 2023-03-17 20:22:27.042975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365c2914f700'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=15), nullable=False),
    sa.Column('capoluogo', sa.String(length=100), nullable=False),
    sa.Column('superficie', sa.Integer(), nullable=False),
    sa.Column('abitanti', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], name='fk_items_categories_id_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('superficie', sa.Integer(), nullable=False),
    sa.Column('abitanti', sa.Integer(), nullable=False),
    sa.Column('regione', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regione'], ['regioni.id'], name='fk_province_regioni_id_regione'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('comuni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('superficie', sa.Integer(), nullable=False),
    sa.Column('abitanti', sa.Integer(), nullable=False),
    sa.Column('regione', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regione'], ['province.id'], name='fk_comuni_province_id_regione'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comuni')
    op.drop_table('province')
    op.drop_table('items')
    op.drop_table('regioni')
    op.drop_table('categories')
    # ### end Alembic commands ###
