"""add sigla

Revision ID: 81b2babbd38b
Revises: 365c2914f700
Create Date: 2023-03-17 22:11:39.193305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b2babbd38b'
down_revision = '365c2914f700'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('province', sa.Column('sigla', sa.String(length=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('province', 'sigla')
    # ### end Alembic commands ###
